version: 2.0

jobs:
    build:
        docker:
            - image: circleci/python:latest
        working_directory: ~/ipc_unix
        steps:
            - checkout
            - run: python -m venv env
            - run: env/bin/pip install -e .
            - run: env/bin/pip install -r dev-requirements.txt
            - run: ./scripts/test.sh
            - run: ./scripts/lint.sh
